### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by sgruhier** [ocombe/ng2-webpack#8]
I don's see anything about source maps, am I wrong?

**Comment by ocombe** [comment]
There's one for TS, but it looks like I haven't activated the SourceMapDevToolPlugin, let me do that :)

**Comment by ocombe** [comment]
Ok my bad, there is already one, it's defined here: https://github.com/ocombe/ng2-webpack/blob/master/webpack.config.js#L28

I will change the dev one to "eval-source-map" so that it point to original sources (instead of compiled ones), but you loose some build speed.
I just checked and the difference is really small on my project right now, but maybe you can change it later if your project gets too big.
